TaskScheduler/urls.py
from django.urls import path

from . import views

app_name = 'taskscheduler'
urlpatterns = [
    # path('', views.prioritySchedule, name='prioritySchedule'),
    path('schedule', views.viewSchedule, name='schedule'),
    path('prepareschedule', views.prepareSchedule, name='prepareschedule'),
    path('createtask', views.createTask, name='createtask'),
    path('tasklist', views.getTasks, name='tasklist'),
    path('deletetask', views.deleteTask, name='deletetask'),
    path('createblocked', views.createBlocked, name='createblocked'),
    path('blockedlist', views.getBlocked, name='blockedlist'),
    path('deleteblocked', views.deleteBlocked, name='deleteblocked'),
    path('createweeklyschedule', views.createWeeklySchedule, name='createweeklyschedule'),
    path('weeklyschedulelist', views.getWeeklySchedule, name='weeklyschedulelist'),
    path('deleteweeklyschedule', views.deleteWeeklySchedule, name='deleteweeklyschedule'),
    path('reportundonetaskasperschedule', views.reportUndoneTaskAsPerSchedule, name='reportundonetaskasperschedule'),
]

myapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	url('taskscheduler/', include('TaskScheduler.urls')),
    url(r'^admin/', admin.site.urls),
]

TaskScheduler/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Task(models.Model):
	def __str__(self):
		return self.name + " (" + str(self.priority) + ")"

	choices = (("0", "Low"), ("1", "Medium"), ("2", "High"))

	name = models.CharField(max_length=200)
	priority = models.CharField(max_length=10, default="0", choices=choices)	# 0->low 1-> medium 2-> high
	span = models.IntegerField(default=60)
	deadline = models.DateTimeField(default=(timezone.now()+timezone.timedelta(minutes=10*60)))
	at_a_stretch = models.IntegerField(default=60)	# how much time you need to do this task once started (in one sitting)
	left = models.IntegerField(default=60)	# time left to complete the task
	done = models.BooleanField(default=False)
	max_repeats_per_day = models.IntegerField(default=4)
	times_repeated_today = models.IntegerField(default=0)
	break_needed_afterwards = models.IntegerField(default=15)

class Schedule(models.Model):
	task = models.ForeignKey(Task, on_delete=models.CASCADE)
	start_time = models.DateTimeField(default=timezone.now()+timezone.timedelta(minutes=60))
	end_time = models.DateTimeField(default=(timezone.now()+timezone.timedelta(minutes=10*60)))
	done = models.BooleanField(default=True)

class Blocked(models.Model):	# Specially booked time slots
	def __str__(self):
		return self.name
	name = models.CharField(max_length=200, default=None)
	start_time = models.DateTimeField(default=timezone.now()+timezone.timedelta(minutes=60))
	end_time = models.DateTimeField(default=(timezone.now()+timezone.timedelta(minutes=10*60)))

class WeeklySchedule(models.Model):
	def __str__(self):
		return self.name
	name = models.CharField(max_length=200)
	start_time = models.TimeField(default=(timezone.now()+timezone.timedelta(minutes=60)).time())
	end_time = models.TimeField(default=(timezone.now()+timezone.timedelta(minutes=10*60)).time())
	minimum_time_to_devote = models.IntegerField(default=30)
	hard_bound = models.BooleanField(default=True)

class DaysRepeated(models.Model):
	weekly_schedule = models.ForeignKey(WeeklySchedule, on_delete=models.CASCADE)
	day_index = models.IntegerField(default=0)

TaskScheduler/forms.py
from django import forms

class TaskForm(forms.Form):
	name = forms.CharField(label='Task Name', max_length=200)
	# priority = forms.IntegerField(label="Priority")
	# span = forms.IntegerField(label="Span")
	# at_a_stretch = forms.IntegerField(label="At a Stretch(min)")
	# done = forms.BooleanField(label="Done Status")

class BlockedForm(forms.Form):
	name = forms.CharField(label='Blocked Name', max_length=200)
	# start_time = forms.DateTimeField(label="Start Time")
	# end_time = forms.DateTimeField(label="End Time")
	
class WeeklyScheduleForm(forms.Form):
	name = forms.CharField(label='Booked Time Name', max_length=200)
	# start_time = forms.DateTimeField(label="Start Time")
	# end_time = forms.DateTimeField(label="End Time")
	

TaskScheduler/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils import timezone
import datetime
import pytz
from .models import Task, Blocked, WeeklySchedule, DaysRepeated, Schedule
from . import SlackRoundRobinScheduler as SRRS
from . import CRUD as crud
from . import schedulerAlgorithms as scAlgo
from . import forms as Forms
from django.utils.dateparse import parse_date
import json
import os

class WeeklyScheduleTemp():
	def __init__(self, name, start_time, end_time):
		self.name = name
		self.start_time = start_time
		self.end_time = end_time

SERVER_URL = "http://localhost:8000"
if os.environ.get("SERVER_URL"):
	SERVER_URL = str(os.environ["SERVER_URL"])

print("SERVER_URL: " + SERVER_URL)

calcutta = pytz.timezone("Asia/Calcutta")

def convertToDateTime(date_string, time_string, *args):
	date = datetime.datetime.strptime(date_string, "%m/%d/%Y").date()
	time = datetime.datetime.strptime(time_string+":00.00000", "%H:%M:%S.%f").time()
	return datetime.datetime.combine(date, time).replace(tzinfo=pytz.UTC)

def getLocalTime(current_time_utc, *args):
	tz = pytz.UTC
	current_time_regional = SRRS.roundToNearestHour(tz.normalize(tz.localize((current_time_utc).replace(tzinfo=None))).astimezone(pytz.timezone("Asia/Calcutta")).replace(tzinfo=pytz.UTC))
	return current_time_regional

# Create your views here.
def prioritySchedule(request):
	tasks = crud.readUndoneTasks()
	blocked = crud.readBlocked(timezone.now())
	taskList = list()
	for t in tasks:
		taskList.append(t)

	blockedList = list()
	for b in blocked:
		blockedList.append(b)

	schedule = scAlgo.scheduleTasks(taskList, blockedList)
	response = ""
	i = 0
	for s in schedule:
		i += 1
		response += str(i) + ") Task name: " + s.task.name + ", start: " + str(s.start_time) + ", end: " + str(s.end_time) + "<br>"
		s.save()
		# print("Task name: " + s.task.name + ", duration: " + str((s.end_time - s.start_time).total_seconds()/60))

	return HttpResponse(response)
	# return render(request, 'schedule.html', {'schedule': schedule})

def reportUndoneTaskAsPerSchedule(request):
	current_time_utc = timezone.now()
	current_time_regional = getLocalTime(current_time_utc)	# + timezone.timedelta(minutes=360)
	if request.method == "POST":
		if request.POST["id"]:
			[success, error] = crud.updateScheduleStatus(request.POST["id"], current_time_regional, False)
			if success:
				return HttpResponse(json.dumps({"success": success, "msg": "Task maked as undone in timeline!"}), content_type="application/json")
			else:
				return HttpResponse(json.dumps({"success": success, "msg": error}), content_type="application/json")
		else:
			return HttpResponse(json.dumps({"success": False, "msg": "ID not mentioned in request!"}), content_type="application/json")
	else:
		return HttpResponse(json.dumps({"success": False, "msg": "Get Method not Supported for this URL!"}), content_type="application/json")

def viewSchedule(request):
	schedule = crud.readSchedule()
	blocked = crud.readBlocked()
	weekly_schedule = crud.getWeeklySchedulePerDayAsList()
	# Logic to render weekly schedule
	# current_time = min(schedule[0].start_time, blocked[0].start_time)
	weekly_schedule_list = list()
	index = 0
	schedule_length = len(schedule)
	for s in schedule:
		if index < schedule_length - 1:
			current_end_time = schedule[index].end_time	# or s.end_time
			next_start_time = schedule[index+1].start_time
			current_day = current_end_time.weekday()
			current_date = current_end_time.date()
			for w in weekly_schedule[current_day]:
				if w.weekly_schedule.hard_bound:
					if w.weekly_schedule.start_time >= current_end_time.time() and w.weekly_schedule.end_time <= next_start_time.time():
						weekly_schedule_list.append(WeeklyScheduleTemp(w.weekly_schedule.name, datetime.datetime.combine(current_date, w.weekly_schedule.start_time).replace(tzinfo=pytz.UTC), datetime.datetime.combine(current_date, w.weekly_schedule.end_time).replace(tzinfo=pytz.UTC)))
				else:
					if w.weekly_schedule.end_time <= next_start_time.time() and  (datetime.datetime.combine(current_date, w.weekly_schedule.end_time).replace(tzinfo=pytz.UTC) - current_end_time).total_seconds()/60 >= w.weekly_schedule.minimum_time_to_devote:
						weekly_schedule_list.append(WeeklyScheduleTemp(w.weekly_schedule.name, datetime.datetime.combine(current_date, w.weekly_schedule.start_time).replace(tzinfo=pytz.UTC), datetime.datetime.combine(current_date, w.weekly_schedule.end_time).replace(tzinfo=pytz.UTC)))
		index += 1
	print("Weekly Schedule list:")
	for w in weekly_schedule_list:
		print("Name: " + w.name + ", start_time: " + str(w.start_time) + ", end_time: " + str(w.end_time))
	return render(request, 'schedule.html', {
		'schedule': [s for s in schedule],
		'blocked': [b for b in blocked],
		'weekly_schedule': weekly_schedule_list,
		'SERVER_URL': SERVER_URL
	})

def prepareSchedule(request):	## Vimp - current timezone is set to India's, change it to take into account actual local timezone 
	for t in Task.objects.all():	# Added here so that reading schedule__task objects don't read old data
		t.times_repeated_today = 0
		t.left = t.span
		t.save()

	current_time_utc = timezone.now()
	current_time_regional = getLocalTime(current_time_utc)
	# current_time_regional -= timezone.timedelta(minutes=720)
	print("Current Regional Time: " + str(current_time_regional))
	schedules_till_now = crud.readPastSchedulesAsList(current_time_regional)
	# print("Past Schedules: " + str(len(schedules_till_now)))
	# for s in schedules_till_now:
	# 	print("Past Schedule name: " + s.task.name)
	max_end_time = current_time_regional
	for s in schedules_till_now:
		max_end_time = max(max_end_time, s.end_time)
		if s.task.done:
			s.task.left = 0
			s.task.save()
			continue
		if s.done:
			s.task.left -= (s.end_time - s.start_time).total_seconds()/60
			if s.task.left <= 0:
				s.task.done = True
			if s.end_time.weekday() == current_time_regional.weekday():
				s.task.times_repeated_today += 1
			s.task.save()

	current_time_regional = max(max_end_time, current_time_regional)
	tasks = crud.readUndoneTasks()
	blocked = crud.readBlocked(current_time_regional)
	weekly_schedule = crud.getWeeklySchedulePerDayAsList()
	taskList = list()
	for t in tasks:
		taskList.append(t)
	blockedList = list()
	for b in blocked:
		blockedList.append(b)

	schedule = SRRS.scheduleTasks(taskList, current_time_regional, blockedList, weekly_schedule)

	print("Schedule: ")
	for s in schedule:
		print("Task name: " + s.task.name + ", start: " + str(s.start_time) + ", end: " + str(s.end_time))
		s.save()

	return HttpResponse(json.dumps({"success": True, "msg": "Schedule Created Successfully!"}), content_type="application/json")

def createTask(request):
	if request.method == "POST":
		data = dict()
		print("Date: " + str(request.POST["deadline_date"]) + ", Time: " + str(request.POST["deadline_time"]))
		if "id" in request.POST:
			data["id"] = request.POST["id"]
		data["name"] = request.POST["name"]
		data["priority"] = request.POST["priority"]
		data["span"] = request.POST["span"]
		data["deadline"] = convertToDateTime(request.POST["deadline_date"], request.POST["deadline_time"])
		data["at_a_stretch"] = request.POST["at_a_stretch"]
		data["done"] = False
		data["max_repeats_per_day"] = request.POST["max_repeats_per_day"]
		data["times_repeated_today"] = 0
		data["break_needed_afterwards"] = request.POST["break_needed_afterwards"]
		# aware_datetime = datetime.datetime.strptime(data["deadline"]+":00", "%Y-%m-%dT%H:%M:%S").replace(tzinfo=pytz.UTC)
		# data["deadline"] = aware_datetime
		print(data["name"]+", "+str(data["priority"])+", "+str(data["span"])+", "+str(data["deadline"])+", "+str(data["at_a_stretch"]))
		if "id" in request.POST:
			[success, error] = crud.createTask(name=data["name"], priority=data["priority"], span=data["span"], deadline=data["deadline"], at_a_stretch=data["at_a_stretch"], done=False, max_repeats_per_day=data["max_repeats_per_day"], times_repeated_today=data["times_repeated_today"], break_needed_afterwards=data["break_needed_afterwards"], id=data["id"])
		else:
			[success, error] = crud.createTask(name=data["name"], priority=data["priority"], span=data["span"], deadline=data["deadline"], at_a_stretch=data["at_a_stretch"], done=False, max_repeats_per_day=data["max_repeats_per_day"], times_repeated_today=data["times_repeated_today"], break_needed_afterwards=data["break_needed_afterwards"])
		if success and "id" in request.POST:
			return HttpResponse(json.dumps({"msg": "Task Updated Successfully."}), content_type="application/json")
		elif success:
			return HttpResponse(json.dumps({"msg": "Task Created Successfully."}), content_type="application/json")
		else:
			return HttpResponse(json.dumps({"error": error}), content_type="application/json")
	else:
		return render(request, 'createTask.html', {
			'form': Forms.TaskForm,
			'SERVER_URL': SERVER_URL
		})

def getTasks(request):
	# if this is a POST request we need to process the form data
	tasks = crud.readAllTasks()
	return render(request, 'taskList.html', {
		'tasks': tasks,
		'SERVER_URL': SERVER_URL
	})

def deleteTask(request):
	# if this is a POST request we need to process the form data
	if request.method == "POST":
		data = request.POST
		print("Id: " + data["id"])
		# t = Task.objects.filter(pk=data["id"])
		# t.delete()
		[success, error] = crud.deleteTaskById(task_id=data["id"])
		if success:
			return HttpResponse(json.dumps({"msg": "Task Deleted Successfully."}), content_type="application/json")
		else:
			return HttpResponse(json.dumps({"error": error}), content_type="application/json")
		# if form.is_valid():
		# 	data = form.cleaned_data
		# 	print(data["name"]+", "+str(data["priority"])+", "+str(data["span"])+", "+str(data["deadline"])+", "+str(data["at_a_stretch"]))
	else:
		return HttpResponse("Non POST methods not supported.")

def createBlocked(request):
	if request.method=="POST":
		data = dict()
		if "id" in request.POST:

TaskScheduler/templates/createTask.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.1.3-dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}">
<script defer src="{% static 'fontawesome/js/fontawesome-all.min.js' %}"></script>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'bootstrap-4.1.3-dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>

<style type="text/css">
	body {
		background-color: #f0fff0;
		color: #240090;
		/*font-family: "Times New Roman", Times, serif;
		font-size: 20px;*/
	}
	.navbar-default {
		background-color: #1034A6;
		height: 80px;
		font-size: 18px;
		font-weight: bold;
	}
	.navbar-default .navbar-brand {
		color: #FFFF33	;
		font-weight: bold;
		font-size: 25px;
	}
	label {
		font-weight: bold;
	}
	button {
		background-color: #7EF9FF;
	}
	ul > li {
		border-style: solid;
		border-right-width: 2px;
		border-left-width: 0px;
		border-top-width: 0px;
		border-bottom-width: 0px;
		border-color: #000000;
	}
	ul .active {
		-webkit-box-shadow: 0px 2px 0px #000000;
		-moz-box-shadow: 0px 2px 0px #000000;
		box-shadow: 0px 2px 0px #000000;
	}
	ul .active > a {
		color: #ADFF2F;
	}
	ul > li > a {
		color: #FFFF33;
	}

	/* The snackbar - position it at the bottom and in the middle of the screen */
	#snackbarMessage {
	    visibility: hidden; /* Hidden by default. Visible on click */
	    min-width: 250px; /* Set a default minimum width */
	    margin-left: -125px; /* Divide value of min-width by 2 */
	    background-color: #333; /* Black background color */
	    color: #fff; /* White text color */
	    text-align: center; /* Centered text */
	    border-radius: 2px; /* Rounded borders */
	    padding: 16px; /* Padding */
	    position: fixed; /* Sit on top of the screen */
	    z-index: 1; /* Add a z-index if needed */
	    left: 50%; /* Center the snackbar */
	    bottom: 30px; /* 30px from the bottom */
	}

	/* Show the snackbar when clicking on a button (class added with JavaScript) */
	#snackbarMessage.show {
	    visibility: visible; /* Show the snackbar */
	    /* Add animation: Take 0.5 seconds to fade in and out the snackbar. 
	   However, delay the fade out process for 2.5 seconds */
	   -webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;
	   animation: fadein 0.5s, fadeout 0.5s 2.5s;
	}
	/* The snackbar - position it at the bottom and in the middle of the screen */

	/* Animations to fade the snackbar in and out */
	@-webkit-keyframes fadein {
	    from {bottom: 0; opacity: 0;} 
	    to {bottom: 30px; opacity: 1;}
	}

	@keyframes fadein {
	    from {bottom: 0; opacity: 0;}
	    to {bottom: 30px; opacity: 1;}
	}

	@-webkit-keyframes fadeout {
	    from {bottom: 30px; opacity: 1;} 
	    to {bottom: 0; opacity: 0;}
	}

	@keyframes fadeout {
	    from {bottom: 30px; opacity: 1;}
	    to {bottom: 0; opacity: 0;}
	}

	.show {
		color: red;
		display: block;
		margin-left: 2%;
	}
	.hide {
		display: none;
		margin-left: 2%;
	}
</style>

<!-- <nav class="navbar navbar-expand-sm bg-dark navbar-dark"> -->
<nav class="navbar navbar-expand-sm navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">Task Scheduler</a>
		</div>
		<ul class="nav navbar-nav">
			<li class="nav-item active">
				<a class="nav-link" href="/taskscheduler/createtask">Create Task</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/taskscheduler/tasklist">View Tasks</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/taskscheduler/schedule">Schedule</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/taskscheduler/createblocked">Create Permanent Task</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/taskscheduler/blockedlist">View Permanent Tasks</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/taskscheduler/createweeklyschedule">Create Weekly Schedule</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/taskscheduler/weeklyschedulelist">View Weekly Schedule</a>
			</li>
		</ul>
	</div>
</nav>

<div id="errorDiv" class="hide"></div>
<form id="taskForm" class="form-horizontal" method="post" novalidate style="margin-left: 2%; margin-top: 2%;">
	{% csrf_token %}
	<div class="form-group row">
		<label class="control-label col-sm-2" for="id_name">Task Name:</label>
		<div class="col-sm-4">
			<input type="text" class="form-control" name="name" id="id_name" placeholder="Enter Task Name">
		</div>
	</div>
	<div class="form-group row">
		<label class="control-label col-sm-2" for="id_priority">Priority:</label>
		<div class="col-sm-4">
			<input type="number" class="form-control" name="priority" id="id_priority" placeholder="Enter Task Priority">
		</div>
	</div>
	<div class="form-group row">
		<label class="control-label col-sm-2" for="id_span">Span(in minutes):</label>
		<div class="col-sm-4">
			<input type="number" class="form-control" name="span" id="id_span" placeholder="Enter Task Span">
		</div>
	</div>
	<div class="form-group row">
		<label class="control-label col-sm-2" for="id_deadline_date">Deadline:</label>
		<div class="col-sm-2">
			<input type="text" class="form-control" name="deadline_date" id="id_deadline_date">
		</div>
		<div class="col-sm-2">
			<input type="time" class="form-control" name="deadline_time" id="id_deadline_time">
		</div>
	</div>
	<div class="form-group row">
		<label class="control-label col-sm-2" for="id_at_a_stretch">At a Stretch(minutes):</label>
		<div class="col-sm-4"> 
			<input type="number" class="form-control" name="at_a_stretch" id="id_at_a_stretch" placeholder="Enter At a Stretch for Task">
		</div>
	</div>
	<div class="form-group row">
		<label class="control-label col-sm-2" for="id_max_repeats_per_day">Repeats per Day:</label>
		<div class="col-sm-4">
			<input type="number" class="form-control" name="max_repeats_per_day" id="id_max_repeats_per_day" placeholder="Enter Repeats per Day">
		</div>
	</div>
	<div class="form-group row">
		<label class="control-label col-sm-2" for="id_break_needed_afterwards">Break Needed Afterwards(minutes):</label>
		<div class="col-sm-4">
			<input type="number" class="form-control" name="break_needed_afterwards" id="id_break_needed_afterwards" placeholder="Enter Break Time Needed After 1 Round Task Completion">
		</div>
	</div>
	<div class="form-group row"> 
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-default">Submit</button>
		</div>
	</div>
</form>

<!-- Snackbars -->
<div id="snackbarMessage"></div>

{% block javascript %}
<script type="text/javascript">
	var SERVER_URL = "{{ SERVER_URL }}";
	console.log("SERVER_URL: ", SERVER_URL);
	function checkValidForm(data) {
		if (data["name"] == "" || data["name"] == null) {
			$("#errorDiv").removeClass("hide");
			$("#errorDiv").html("<b>*Name should not be blank</b>");
			$("#errorDiv").addClass("show");
			return;
		}
		if (isNaN(data["priority"]) || data["priority"] === "" || data["priority"] == null) {
			$("#errorDiv").removeClass("hide");
			$("#errorDiv").html("<b>*Priority should be a number</b>");
			$("#errorDiv").addClass("show");
			return false;
		}
		if (isNaN(data["span"]) || data["span"] === "" || data["span"] == null) {
			$("#errorDiv").removeClass("hide");
			$("#errorDiv").html("<b>*Span should be a number</b>");
			$("#errorDiv").addClass("show");
			return false;
		}
		if (data["deadline_date"] === "" || data["deadline_date"] == null) {
			$("#errorDiv").removeClass("hide");
			$("#errorDiv").html("<b>*Select a valid Deadline Date</b>");
			$("#errorDiv").addClass("show");
			return false;
		}
		if (data["deadline_time"] === "" || data["deadline_time"] == null) {
			$("#errorDiv").removeClass("hide");
			$("#errorDiv").html("<b>*Select a valid Deadline Time</b>");
			$("#errorDiv").addClass("show");
			return false;
		}
		if (isNaN(data["at_a_stretch"]) || data["at_a_stretch"] === "" || data["at_a_stretch"] == null) {
			$("#errorDiv").removeClass("hide");
			$("#errorDiv").html("<b>*At a stretch should be a number</b>");
			$("#errorDiv").addClass("show");
			return false;
		}
		if (isNaN(data["max_repeats_per_day"]) || data["max_repeats_per_day"] === "" || data["max_repeats_per_day"] == null) {
			$("#errorDiv").removeClass("hide");
			$("#errorDiv").html("<b>*Max repeats per day should be a number</b>");
			$("#errorDiv").addClass("show");
			return false;
		}
		if (isNaN(data["break_needed_afterwards"]) || data["break_needed_afterwards"] === "" || data["break_needed_afterwards"] == null) {
			$("#errorDiv").removeClass("hide");
			$("#errorDiv").html("<b>*Break needded afterwards should be a number</b>");
			$("#errorDiv").addClass("show");
			return false;
		}
		if (new Date() >= new Date(data["deadline_date"].concat(" ", data["deadline_time"]))) {
			$("#errorDiv").removeClass("hide");
			$("#errorDiv").html("<b>*Select a date-time in the future!</b>");
			$("#errorDiv").addClass("show");
			return false;
		}
		return true;
	}
	$(function() {
		function getCookie(name) {
			var cookieValue = null;
				if (document.cookie && document.cookie != '') {
				var cookies = document.cookie.split(';');
					for (var i = 0; i < cookies.length; i++) {
					var cookie = jQuery.trim(cookies[i]);
					// Does this cookie string begin with the name we want?
					if (cookie.substring(0, name.length + 1) == (name + '=')) {
						cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
						break;
					}
				}
			}
			return cookieValue;
		}
		$("#id_deadline_date").datepicker();
		$("#id_deadline_date").datepicker("option", "showAnim", "slideDown");
		$('#taskForm').submit(function(e) {
			e.preventDefault();
			let data = {};
			data["name"] = $("#id_name").val();
			data["priority"] = $("#id_priority").val();
			data["span"] = $("#id_span").val();
			data["deadline_date"] = $("#id_deadline_date").val();
			data["deadline_time"] = $("#id_deadline_time").val();
			data["at_a_stretch"] = $("#id_at_a_stretch").val();
			data["max_repeats_per_day"] = $("#id_max_repeats_per_day").val();
			data["break_needed_afterwards"] = $("#id_break_needed_afterwards").val();
			if (!checkValidForm(data)) {
				return;
			}
			console.log("Data for creating task: ", data);
			$.ajax({
				url: SERVER_URL.concat("/taskscheduler/createtask"),
				contentType: "application/x-www-form-urlencoded",
				type: "POST",
				headers: {
					"X-CSRFToken": getCookie('csrftoken')
				},
				data: data,
				dataType: 'json',
				success: function (data) {
					if (data.error) {
						$("#snackbarMessage").text(data.error);
					} else {
						$("#snackbarMessage").text(data.msg);
					}
					$("#snackbarMessage").addClass("show");
					setTimeout(function(){
						$("#snackbarMessage").removeClass("show"); $("#snackbarMessage").addClass("");
					}, 3000);
				}
			});
		});
	});
</script>
{% endblock %}

TaskScheduler/templates/task.html
<form method="post" novalidate>
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit">
</form>